"""add sas_url_encrypted to azure_publish_config

Revision ID: c65c93e76dd6
Revises: f8d592766570
Create Date: 2026-09-09 14:30:07.215132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c65c93e76dd6'
down_revision: Union[str, None] = 'f8d592766570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here (unlike the initial CREATE TABLE) since
    # this ADD COLUMN runs against an existing table that may already have a
    # row (the seeded config), which a NOT NULL column with no default would
    # violate.
    op.add_column(
        'azure_publish_config',
        sa.Column('sas_url_encrypted', sa.String(length=4096), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azure_publish_config', 'sas_url_encrypted')
    # ### end Alembic commands ###
