"""initial schema

Revision ID: f8d592766570
Revises: 
Create Date: 2026-09-08 16:48:10.344279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8d592766570'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_or_cidr', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_or_cidr')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=120), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('azure_publish_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_string_encrypted', sa.String(length=4096), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('blob_prefix', sa.String(length=255), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('sas_expiry_days', sa.Integer(), nullable=False),
    sa.Column('publish_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('generate_sas', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forticloud_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('client_secret_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('api_gateway', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_feed_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('blob_name', sa.String(length=500), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('blob_url', sa.String(length=2000), nullable=False),
    sa.Column('sas_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_index')
    )
    op.create_table('threat_intel_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.Enum('plain_ip_list', 'csv', 'json', name='threatintelformat'), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_status', sa.String(length=500), nullable=False),
    sa.Column('indicator_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fortigate_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('vdom', sa.String(length=64), nullable=False),
    sa.Column('api_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('site_tag', sa.String(length=120), nullable=False),
    sa.Column('poll_enabled', sa.Boolean(), nullable=False),
    sa.Column('log_source', sa.Enum('device_api', 'forticloud', name='logsource'), nullable=False),
    sa.Column('forticloud_credential_id', sa.String(length=36), nullable=True),
    sa.Column('forticloud_serial', sa.String(length=64), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_status', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forticloud_credential_id'], ['forticloud_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('vpn_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason_text', sa.String(length=500), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['fortigate_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_events_device_time', 'auth_events', ['device_id', 'event_time'], unique=False)
    op.create_index('ix_auth_events_src_ip_time', 'auth_events', ['src_ip', 'event_time'], unique=False)
    op.create_table('blacklist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_or_cidr', sa.String(length=64), nullable=False),
    sa.Column('reason_type', sa.Enum('brute_force', 'threat_intel', 'manual', name='blacklistreason'), nullable=False),
    sa.Column('reason_detail', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'removed', name='blackliststatus'), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['fortigate_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blacklist_ip_status', 'blacklist_entries', ['ip_or_cidr', 'status'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('threshold_count', sa.Integer(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['fortigate_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_cursors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('log_type', sa.String(length=32), nullable=False),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['fortigate_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'log_type', name='uq_poll_cursor_device_logtype')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_cursors')
    op.drop_table('detection_rules')
    op.drop_index('ix_blacklist_ip_status', table_name='blacklist_entries')
    op.drop_table('blacklist_entries')
    op.drop_index('ix_auth_events_src_ip_time', table_name='auth_events')
    op.drop_index('ix_auth_events_device_time', table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_table('fortigate_devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('threat_intel_sources')
    op.drop_table('published_feed_parts')
    op.drop_table('forticloud_credentials')
    op.drop_table('azure_publish_config')
    op.drop_table('audit_log')
    op.drop_table('allowlist_entries')
    # ### end Alembic commands ###
